services:
  clickhouse-server:
    restart: always
    image: altinity/clickhouse-server:24.3.18.10426.altinitystable
    profiles: ["ci"]
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse  # persistent storage
      - clickhouse_configs:/etc/clickhouse-server  # optional for custom configs
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: mysecurepassword123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    
  clickhouse-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    profiles: ["ci"]
    environment:
      VITE_CLICKHOUSE_URL: http://localhost:8123
      VITE_CLICKHOUSE_USER: default
      VITE_CLICKHOUSE_PASS: mysecurepassword123
      VITE_CLICKHOUSE_USE_ADVANCED: true
    ports:
      - "5521:5521"
    

  clickhouse-migrate:
    image: rust:latest
    profiles: ["ci", "migrate"]
    depends_on:
      - clickhouse-server
    volumes:
      - ./ch_migrations:/chm/ch_migrations
    working_dir: /chm/
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      sed -i 's|^url = .*|url = \"http://clickhouse-server:8123\"|' ch_migrations/chm.toml && \
      touch .env && \
      cargo install chm && chm migration run && \
      sed -i 's|^url = .*|url = \"http://localhost:8123\"|' ch_migrations/chm.toml
      "

  exporter:
    restart: always
    build: .
    container_name: rcosmos-exporter
    volumes:
      - ./config.yaml:/config.yaml:ro
    ports:
      - "9100:9100" # exporter metrics endpoint
    environment:
      - NODE_NAME=local-exporter
      - CLICKHOUSE_URL=http://clickhouse-server:8123
      - CLICKHOUSE_DATABASE=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mysecurepassword123
        
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles: ["ci"]
    volumes:
      - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - exporter
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles: ["ci"]
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    links:
      - prometheus
    volumes:
      - ./.docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./.docker/grafana/dashboards:/var/lib/grafana/dashboards  
      - ./.docker/grafana/dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./.docker/grafana/plugins:/var/lib/grafana/plugins
    

volumes:
  clickhouse_data:
  clickhouse_configs:
  prometheus_data:
  grafana_data: