[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.run-mainnet]
command = "cargo"
args = ["run", "--", "--env", "test-envs/.env.${@}.mainnet"]

[tasks.run-testnet]
command = "cargo"
args = ["run", "--", "--env", "test-envs/.env.${@}.testnet"]

[tasks.rcosmos]
dependencies = [
    "format",
    "build",
    "test"
]