apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      host: clickhouse-server
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: "mysecurepassword123" 