{
 "title": "CometBFT Network",
 "tags": [
  "cometbft",
  "blockchain",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "SELECT chain_id FROM validators"
   }
  ]
 },
 "panels": [
  { "title": "Uptimes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "1 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_uptime{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "1 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "1 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "1 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "7 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_uptime{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "7 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "7 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "7 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "15 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_uptime{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "15 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 17 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "15 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 17 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "15 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "30 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_uptime{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "30 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 25 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "30 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 25 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "30 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  { "title": "Signatures over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Validator Signatures",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "WITH (\n  SELECT max(height) FROM validators_signatures WHERE chain_id = '${chain_id}'\n) AS max_height\nSELECT\n  height,\n  address,\n  signed\nFROM validators_signatures\nWHERE height >= max_height - 80 AND chain_id = '${chain_id}' AND address != ''\nORDER BY height ASC\n"
    }
   ]
  }
 ]
}