{
 "title": "Cosmos Dashboard",
 "description": "Tendermint  based blockchains",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(tendermint_current_block_height,network)"
    }
   },
   {
    "name": "chain_id",
    "label": "ChainID",
    "query": {
     "query": "label_values(tendermint_validators{network=\"$network\"},chain_id)"
    }
   },
   {
    "name": "name",
    "label": "Validator Name",
    "query": {
     "query": "label_values(tendermint_validators{chain_id=\"$chain_id\"},name)"
    }
   },
   {
    "name": "address",
    "label": "Address",
    "query": {
     "query": "label_values(tendermint_validators{chain_id=\"$chain_id\", name=\"$name\"},address)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(tendermint_node_id{chain_id=\"$chain_id\"},name)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Status (Sync)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_node_catching_up{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_node_latest_block_height{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "tendermint_node_catching_up{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_node_latest_block_time{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"} * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Binary Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(tendermint_node_app_version{chain_id=\"$chain_id\", name=\"$node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binary",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(tendermint_node_app_name{chain_id=\"$chain_id\", name=\"$node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binary  Commit Hash",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(tendermint_node_app_commit{chain_id=\"$chain_id\", name=\"$node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Moniker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(tendermint_node_moniker{chain_id=\"$chain_id\", name=\"$node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cosmos SDK Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(tendermint_node_cosmos_sdk_version{chain_id=\"$chain_id\", name=\"$node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "[$interval]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\".*irq\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Interrupts"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"iowait\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "IOwait"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"nice\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Nice"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"steal\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Steal"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|user|system|iowait|.*irq|steal|nice\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\",network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{network=\"$network\",nick=\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "count(up{network=\"$network\",nick=\"$node\"}) by(nick)",
     "legendFormat": "Hostname: [{{nick}}]"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "description": "[$interval]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{network=\"$network\",nick=~\"$node\"} - node_memory_MemFree_bytes{network=\"$network\",nick=~\"$node\"} - (node_memory_Cached_bytes{network=\"$network\",nick=~\"$node\"} + node_memory_Buffers_bytes{network=\"$network\",nick=~\"$node\"}))",
     "legendFormat": "Used"
    },
    {
     "expr": "max(node_memory_Cached_bytes{network=\"$network\",nick=~\"$node\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{network=\"$network\",nick=~\"$node\"})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{network=\"$network\",nick=~\"$node\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "max((node_memory_SwapTotal_bytes{nick=~\"$node\",network=\"$network\"} - node_memory_SwapFree_bytes{nick=~\"$node\",network=\"$network\"}))",
     "legendFormat": "Swap"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes{nick=~\"$node\",network=\"$network\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(up{nick=\"$node\",network=\"$network\"}) by (nick)",
     "legendFormat": "Hostname: [{{nick}}]"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{nick=~\"$node\",network=\"$network\"}",
     "legendFormat": "Avail"
    }
   ]
  },
  {
   "title": "Disk Bytes",
   "type": "timeseries",
   "description": "[$interval] Completed disk bytes for selected device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{network=~\"$network\",nick=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{network=~\"$network\",nick=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Write bytes"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{network=\"$network\", nick=\"$node\"}[$__rate_interval])",
     "legendFormat": "Read bytes {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{network=\"$network\", nick=\"$node\"}[$__rate_interval])",
     "legendFormat": "Write bytes {{device}}"
    }
   ]
  },
  {
   "title": "Disks IOPS",
   "type": "timeseries",
   "description": "Completed disks IOPS ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_disk_reads_completed_total{network=\"$network\", nick=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Read IOPS - {{device}}"
    },
    {
     "expr": "sum by (device) (irate(node_disk_writes_completed_total{network=\"$network\",nick=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Write IOPS - {{device}}"
    }
   ]
  },
  {
   "title": "Bytes used",
   "type": "timeseries",
   "description": "Bytes usage for mountpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{network=\"$network\", nick=\"$node\"} - node_filesystem_avail_bytes{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "Used - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_avail_bytes{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "Free - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "Size - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk busy",
   "type": "timeseries",
   "description": "Disks busy for devices",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_disk_io_time_seconds_total{network=\"$network\", nick=~\"$node\"})[$__rate_interval])",
     "legendFormat": "busy {{device}}"
    },
    {
     "expr": "count by (device) (irate(node_disk_io_time_seconds_total{network=\"$network\", nick=~\"$node\"}[$__rate_interval])) - sum by (device) (irate(node_disk_io_time_seconds_total{network=\"$network\", nick=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "free {{device}}"
    },
    {
     "expr": "count by (device) (irate(node_disk_io_time_seconds_total{network=\"$network\", nick=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "total {{device}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "tendermint_node_latest_block_height{chain_id=\"$chain_id\", name=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_node_latest_block_height{chain_id=\"$chain_id\", name=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Earliest Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_node_earliest_block_height{chain_id=\"$chain_id\", name=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "tendermint_node_latest_block_time{chain_id=\"$chain_id\", name=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Latest Block Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_node_latest_block_time{chain_id=\"$chain_id\", name=\"$node\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Earliest Block Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_node_earliest_block_time{chain_id=\"$chain_id\", name=\"$node\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cometbft_p2p_peers{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 53 },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "{{nick}}"
    },
    {
     "expr": "cometbft_p2p_peers{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "{{nick}}"
    }
   ]
  },
  {
   "title": "Peer Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_peer_send_bytes_total{network=\"$network\", nick=\"$node\"}[$__rate_interval]) )",
     "legendFormat": "{{nick}}"
    },
    {
     "expr": "sum(rate(tendermint_p2p_peer_send_bytes_total{network=\"$network\", nick=\"$node\"}[$__rate_interval]) )",
     "legendFormat": "{{nick}}"
    }
   ]
  },
  {
   "title": "Peer Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_peer_receive_bytes_total{network=\"$network\", nick=\"$node\"}[$__rate_interval]) )",
     "legendFormat": "{{nick}}"
    },
    {
     "expr": "sum(rate(tendermint_p2p_peer_receive_bytes_total{network=\"$network\", nick=\"$node\"}[$__rate_interval]) )",
     "legendFormat": "{{nick}}"
    }
   ]
  },
  {
   "title": "Mempool Tx's",
   "type": "timeseries",
   "description": "Number of uncommitted transactions in the mempool",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "{{nick}}"
    },
    {
     "expr": "cometbft_mempool_size{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "{{nick}}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "description": "Number of uncommitted transactions in the mempool",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size_bytes{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "{{nick}}"
    },
    {
     "expr": "tendermint_mempool_size{network=\"$network\", nick=\"$node\"}",
     "legendFormat": "{{nick}}"
    }
   ]
  },
  {
   "title": "P95 method latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cometbft_abci_connection_method_timing_seconds_bucket{network=\"$network\", nick=\"$node\"}[$__rate_interval])) by (le, method))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tendermint_abci_connection_method_timing_seconds_bucket{network=\"$network\", nick=\"$node\"}[$__rate_interval])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average method latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_abci_connection_method_timing_seconds_sum{network=\"$network\", nick=\"$node\"}[5m])\n/\nrate(cometbft_abci_connection_method_timing_seconds_count{network=\"$network\", nick=\"$node\"}[5m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "rate(tendermint_abci_connection_method_timing_seconds_sum{network=\"$network\", nick=\"$node\"}[5m])\n/\nrate(tendermint_abci_connection_method_timing_seconds_count{network=\"$network\", nick=\"$node\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RCosmos Exporter Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_exporter_version_info{network=\"$network\", nick=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RCosmos Build Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_exporter_version_info{network=\"$network\", nick=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RCosmos Commit Hash",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_exporter_version_info{network=\"$network\", nick=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Missed blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(\n  tendermint_validator_missed_blocks_total{\n    network=\"$network\",\n    address=\"$address\",\n    cluster=\"cosmos-rpc\"\n  }[$__range]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "timeseries",
   "description": "Missed blocks status",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 77 },
   "targets": [
    {
     "expr": "avg by(name, address) (\r\n  increase(\r\n    tendermint_validator_missed_blocks_total{chain_id=\"$chain_id\", address=\"$address\", k8s_pod_start_time=\"\"}[$interval]\r\n  )\r\n  +\r\n  on(address) group_left(name)\r\n  tendermint_validators{chain_id=\"$chain_id\", name=\"$name\", k8s_pod_start_time=\"\"}\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proposed blocks by $name",
   "type": "timeseries",
   "description": "Proposed blocks",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 77 },
   "targets": [
    {
     "expr": "avg by(name, address) (\r\n  increase(\r\n    tendermint_validator_proposed_blocks_total{chain_id=\"$chain_id\", address=\"$address\", k8s_pod_start_time=\"\"}[$__rate_interval]\r\n  )\r\n  +\r\n  on(address) group_left(name)\r\n  tendermint_validators{chain_id=\"$chain_id\", name=\"$name\", k8s_pod_start_time=\"\"}\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Selected validator uptime",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_uptime{chain_id=\"$chain_id\", address=\"$address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tendermint_validator_uptime{chain_id=\"$chain_id\", address=\"$address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jailed",
   "type": "stat",
   "description": "Validator jailed status",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_jailed{chain_id=\"$chain_id\", address=\"$address\", k8s_pod_start_time=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slashes",
   "type": "stat",
   "description": "Slashes",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_slashes{chain_id=\"$chain_id\", name=\"$name\", address=\"$address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Delegations",
   "type": "stat",
   "description": "Delegations",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_delegations{chain_id=\"$chain_id\", name=\"$name\", address=\"$address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Unbonding delegations",
   "type": "stat",
   "description": "Unbonding Delegations",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_unbonding_delegations{chain_id=\"$chain_id\", name=\"$name\", address=\"$address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Commission Rate",
   "type": "stat",
   "description": "Commission Rate",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_commission_rate{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Rate ",
   "type": "stat",
   "description": "Max Rate",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_commission_max_rate{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Rate Change",
   "type": "stat",
   "description": "Max Rate Change",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_commission_max_rate_change{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delegator Shares",
   "type": "stat",
   "description": "Delegator Shares",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_delegator_share{chain_id=\"$chain_id\", name=\"$name\", address=\"$address\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voting power",
   "type": "stat",
   "description": "Validators voting power",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_voting_power{chain_id=\"$chain_id\", address=\"$address\", k8s_pod_start_time=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Tokens",
   "type": "stat",
   "description": "Validator tokens",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_tokens{chain_id=\"$chain_id\", address=\"$address\", k8s_pod_start_time=\"\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commisions",
   "type": "stat",
   "description": "Commisions",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_commissions{chain_id=\"$chain_id\", name=\"$name\", address=\"$address\"} / 1000000",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "Rewards",
   "type": "stat",
   "description": "Commisions",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_validator_rewards{chain_id=\"$chain_id\", name=\"$name\", address=\"$address\"} / 1000000",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "Proposer Priority",
   "type": "timeseries",
   "description": "Validator tokens",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 95 },
   "targets": [
    {
     "expr": "tendermint_validator_proposer_priority{chain_id=\"$chain_id\", address=\"$address\", k8s_pod_start_time=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Upgrade plan height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_upgrade_plan{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "description": "Recent tendermint block height",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_current_block_height{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "$chain_id"
    }
   ]
  },
  {
   "title": "Last block time",
   "type": "stat",
   "description": "Recent block time",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_current_block_time{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}*1000"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "description": "Block Time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(tendermint_current_block_time{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}[$__rate_interval])/increase(tendermint_current_block_height{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}[$__rate_interval])",
     "legendFormat": "t/h"
    }
   ]
  },
  {
   "title": "Tx's per block",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tendermint_block_txs{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "Tx's"
    }
   ]
  },
  {
   "title": "Block average tx size",
   "type": "barchart",
   "description": "Recent block time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tendermint_block_tx_size{chain_id=\"$chain_id\"}",
     "legendFormat": "Block average tx size"
    }
   ]
  },
  {
   "title": "Block gas used",
   "type": "barchart",
   "description": "Block gas used",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "tendermint_block_gas_wanted{chain_id=\"$chain_id\"}",
     "legendFormat": "Gas used"
    }
   ]
  },
  {
   "title": "Block gas wanted",
   "type": "barchart",
   "description": "Block gas wanted",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 118 },
   "targets": [
    {
     "expr": "tendermint_block_gas_used{chain_id=\"$chain_id\"}",
     "legendFormat": "Gas wanted"
    }
   ]
  },
  {
   "title": "Block tx avg gas wanted",
   "type": "barchart",
   "description": "Average gas wanted by tx's in a block",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "tendermint_block_tx_gas_wanted{chain_id=\"$chain_id\"}",
     "legendFormat": "Gas used"
    }
   ]
  },
  {
   "title": "Block tx avg gas used",
   "type": "barchart",
   "description": "Average gas used by tx's in a block",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 118 },
   "targets": [
    {
     "expr": "tendermint_block_tx_gas_used{chain_id=\"$chain_id\"}",
     "legendFormat": "Gas used"
    }
   ]
  },
  {
   "title": "RCosmos Exporter Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_exporter_version_info{network=\"$network\", k8s_namespace_name=\"exporters\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RCosmos Build Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_exporter_version_info{network=\"$network\", k8s_namespace_name=\"exporters\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RCosmos Commit Hash",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_exporter_version_info{network=\"$network\", k8s_namespace_name=\"exporters\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network stats and proposals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true
  },
  {
   "title": "Active Set",
   "type": "stat",
   "description": "Validators are in active set",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tendermint_validator_voting_power{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Network validators",
   "type": "stat",
   "description": "Validators on the network",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tendermint_validators{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Proposals",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tendermint_proposals{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upgrade proposals",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tendermint_upgrade_status{chain_id=\"$chain_id\", k8s_pod_start_time=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cosmos Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Heartbeats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_exporter_heartbeat{network=\"$network\"} * 1000",
     "legendFormat": "{{nick}}-{{net_host_name}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  rate(rcosmos_exporter_task_error{network=\"$network\"}[15m]) \n  or \n  vector(0)\n) \n/ \nrate(rcosmos_exporter_task_run{network=\"$network\"}[15m])",
     "legendFormat": "{{task}}-{{net_host_name}}"
    }
   ]
  }
 ]
}