{
 "title": "Tendermint Network",
 "tags": [
  "cometbft",
  "blockchain",
  "monitoring",
  "tendermint"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(rcosmos_cometbft_validator,chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Validator Signatures",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH (\n  SELECT max(height) FROM validators_signatures WHERE chain_id = '${chain_id}'\n) AS max_height\nSELECT\n  height,\n  address,\n  signed\nFROM validators_signatures\nWHERE height >= max_height - 40 AND chain_id = '${chain_id}' AND address != ''\nORDER BY height ASC\n"
    },
    {
     "expr": "rcosmos_tendermint_validator{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Uptimes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "1 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_uptime{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "1 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "1 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "1 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_1d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "7 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_uptime{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "7 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "7 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "7 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_7d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "15 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_uptime{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "15 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "15 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "15 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_15d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "30 Day uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_uptime{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "30 Day Signed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_signed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "30 Day Missed Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_missed_blocks{chain_id=\"$chain_id\", address!=\"\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "30 Day Total Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_validator_30d_total_blocks{chain_id=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  { "title": "Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_current_block_height{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_current_block_time{chain_id=\"$chain_id\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(rcosmos_cometbft_current_block_time{chain_id=\"$chain_id\"}[$__rate_interval])/increase(rcosmos_cometbft_current_block_height{chain_id=\"$chain_id\"}[$__rate_interval])",
     "legendFormat": "t/h"
    }
   ]
  },
  {
   "title": "Tx's Per Block",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_block_txs{chain_id=\"$chain_id\"}",
     "legendFormat": "Tx's"
    }
   ]
  },
  {
   "title": "Average Tx Size",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_block_tx_size{chain_id=\"$chain_id\"}",
     "legendFormat": "Avg Tx Size"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_block_gas_used{chain_id=\"$chain_id\"}",
     "legendFormat": "Gas used"
    }
   ]
  },
  {
   "title": "Gas Wanted",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 78 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_block_gas_wanted{chain_id=\"$chain_id\"}",
     "legendFormat": "Gas wanted"
    }
   ]
  },
  {
   "title": "TX Avg Gas Used",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_block_tx_gas_used{chain_id=\"$chain_id\"}",
     "legendFormat": "Tx Avg Gas used"
    }
   ]
  },
  {
   "title": "TX Avg Gas Wanted",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 78 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_block_tx_gas_wanted{chain_id=\"$chain_id\"}",
     "legendFormat": "Tx Avg Gas wanted"
    }
   ]
  },
  { "title": "Upgrade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Upgrade Plan Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_upgrade_plan{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Slashing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Downtime Jail Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_param_downtime_jail_duration{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slash Fraction For Double Sign",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_param_slash_fraction_double_sign{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slash Fraction For Downtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_param_slash_fraction_downtime{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Signed Per Window",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_param_min_signed_per_window{chain_id=\"$chain_id\"} * rcosmos_tendermint_slashing_param_signed_blocks_window{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signed Blocks Window",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_param_signed_blocks_window{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slashing Missed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_missed_blocks{chain_id=\"$chain_id\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Validator Start Height",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_start_height{chain_id=\"$chain_id\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Validator Index Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_index_offset{chain_id=\"$chain_id\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Jailed Until",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_jailed_until{chain_id=\"$chain_id\"} * 1000 + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Validator Tombstoned",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_slashing_tombstoned{chain_id=\"$chain_id\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  { "title": "Staking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Commission Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_commission_rate{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Commission Max Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_commission_max_rate{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Commission Max Rate Change",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_commission_max_rate_change{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Validator Jail",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_jailed{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_tokens{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Delegator Share",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_delegator_share{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Unbonding Delegations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_unbonding_delegations{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Validator Rewards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_rewards{chain_id=\"$chain_id\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}} - {{denom}}"
    }
   ]
  },
  {
   "title": "Commissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_commissions{chain_id=\"$chain_id\"} + on(address, chain_id)\n    group_left(moniker)\n    rcosmos_tendermint_validator",
     "legendFormat": "{{moniker}} - {{denom}}"
    }
   ]
  },
  {
   "title": "Slashes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "rcosmos_tendermint_validator_slashes{chain_id=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  { "title": "Gov", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  {
   "title": "Proposals",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rcosmos_tendermint_proposal{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}