{
 "title": "Tendermint Node",
 "tags": [
  "tendermint",
  "cometbft",
  "blockchain",
  "monitoring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "query": {
     "query": "label_values(rcosmos_cometbft_node_id,chain_id)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values({chain_id=\"$chain_id\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Catching Up",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_node_catching_up{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_node_latest_block_height{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_node_latest_block_height{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Earliest Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_node_earliest_block_height{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rcosmos_cometbft_node_latest_block_time{chain_id=\"$chain_id\", name=\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Latest Block Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_node_latest_block_time{chain_id=\"$chain_id\", name=\"$name\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Earliest Block Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rcosmos_cometbft_node_earliest_block_time{chain_id=\"$chain_id\", name=\"$name\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binary",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_tendermint_node_app_name{chain_id=\"$chain_id\", name=\"$name\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binary Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_tendermint_node_app_version{chain_id=\"$chain_id\", name=\"$name\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cosmos SDK Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_tendermint_node_cosmos_sdk_version{chain_id=\"$chain_id\", name=\"$name\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Moniker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_tendermint_node_moniker{chain_id=\"$chain_id\", name=\"$name\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binary commit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(rcosmos_tendermint_node_app_commit{chain_id=\"$chain_id\", name=\"$name\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}