ame: Release PR
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:

  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE }}

      - uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          package-name: rcosmos-exporter
          pull-request-title-pattern: 'release(${component}): v${version}'
          token: ${{ steps.generate_token.outputs.token }}